### ISSUE TITLE
Check validity of list of wpp countries - fuzzy matching

### ISSUE THREAD

**Issue by chitrams** [chitrams/conmat-testing#1]
Check that the list of countries pulled out of the `wpp_age()` dataset is correct, from the following code:

```R
list_country <- inner_join(list_country, all_countries, by = c("country" = "name"))
list_country <- list_country %>% pull(country) %>% as.character
```

Potential issues:
- `all_countries.csv` may be outdated, so not all the `wpp_age` countries would have been pulled out
- Incongruency of country names/labels
- 183 (`wpp_age`) vs 249 (UN data) countries - why?

**Comment by chitrams** [comment]
Do I just have to go through the entire list one by one to make sure that I'm not missing anything?

**Comment by njtierney** [comment]
I think there should be a way to do a comparison maybe with fuzzy matching? Let's discuss tomorrow :)

**Comment by chitrams** [comment]
Some packages to try:
- Nick recommends `stringdist`, also recommends experimenting and just seeing which one works best
- `fedmatch::merge_plus` apparently works well with `data.table`
- `fuzzyjoin::stringdist_join` utilises `tidyverse` syntax

Next steps:
- [x] Allocate 0.5-1.0h to experiment with these packages, as this will/might be useful going forward w other contact surveys

**Comment by chitrams** [comment]
Hugo Gruson has written an R package [`contactdata`](https://github.com/bisaloo/contactdata) that puts together the social contact data for 177 regions from Prem et al. 2017 and 2021 studies.

Issue with comparing both: we only have 2015 data whilst his package takes contact survey for the years 2020 and 2017.

**Comment by chitrams** [comment]
After initial checks: 
- [ ] Exclude "Western Sahara" from our data, it's not a country
- [ ] "Syrian Arab Republic"? Is this Syria?

**Comment by chitrams** [comment]
New branch is to address this and issue #3

**Comment by chitrams** [comment]
Fuzzy matching with `standardised_country_names` causes issues! `Less developed regions, excluding China` is read as `China`, causing issues in later workflow.

I don't think there's a way of going about this except for manually checking...

**Comment by chitrams** [comment]
> After initial checks:
> 
> * [x]  Exclude "Western Sahara" from our data, it's not a country
> * [ ]  "Syrian Arab Republic"? Is this Syria?

Western Sahara is actually a disputed country. So leaving this in.

**Comment by chitrams** [comment]
@njtierney how much time do you want me to spend on this? The current workflow already works well. Issues are with politically ambiguous countries; we would need to weed them out ourselves, which will take at least another 2 hours for me as I would need to read up on which countries are actually a country based on the UN standards, and then manually change them, and then re-do the targets workflow.

Our current source for validating the country names are [here](https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes). Are we happy to just stick with this (i.e. is this source credible enough for us)?

I don't think it's worth putting more time into this if our ultimate goal is to compare our resulting contact matrices to the 177 from Prem et al.; then we would only need the list of countries that Prem et al. uses.

**Comment by chitrams** [comment]
Countries in Prem not in our `wpp`-based data:
- Andorra
- Monaco
- North Macedonia
- South Korea
- Tanzania
- United Kingdom

Errors
- Hong Kong (named "China, Hong Kong SAR" in `wpp`)
- Taiwan (named "China, Taiwan province of China" in `wpp`)

Countries in our `wpp`-based data but not in Prem:
```
 [1] "Afghanistan"              "Angola"                  
 [3] "Aruba"                    "Barbados"                
 [5] "Burundi"                  "Central African Republic"
 [7] "Chad"                     "Comoros"                 
 [9] "Cuba"                     "Djibouti"                
[11] "Equatorial Guinea"        "Eritrea"                 
[13] "French Guiana"            "French Polynesia"        
[15] "Gabon"                    "Gambia"                  
[17] "Grenada"                  "Guadeloupe"              
[19] "Guam"                     "Guinea-Bissau"           
[21] "Libya"                    "Madagascar"              
[23] "Malawi"                   "Mali"                    
[25] "Martinique"               "Mayotte"                 
[27] "Myanmar (Burma)"          "New Caledonia"           
[29] "Norway"                   "Papua New Guinea"        
[31] "Puerto Rico"              "St. Vincent & Grenadines"
[33] "Somalia"                  "South Sudan"             
[35] "Sudan"                    "Togo"                    
[37] "Trinidad & Tobago"        "Turkmenistan"            
[39] "Western Sahara"         
```
