### ISSUE TITLE
How to refer to a col name inside a fn? For `standardise_country_name` fn

### ISSUE THREAD

**Issue by chitrams** [chitrams/conmat-testing#14]
Here is the code:

```R
standardise_country_name <- function(data, var_in){
  countrycode::countryname(glue("{data}${var_in}"),
                           destination = "country.name.en",
                           nomatch = NA,
                           warn = TRUE)
}
```

I know something's wrong with `glue("{data}${var_in})"`.

There was something you needed to do to refer to var names within a fn, `assign` or `refer` or something at the beginning of the function?

What is this concept called?

**Comment by njtierney** [comment]
This is a good question! This general area is called metaprogramming, and in R we often call this non standard evaluation.

What are the inputs that you'd expect to `standardise_country_name()`?

If you want to specify the variable name as text you can do

```r
standardise_country_name <- function(data, var_in){
  countrycode::countryname(data[[var_in]],
                           destination = "country.name.en",
                           nomatch = NA,
                           warn = TRUE)
}
```

But if you're going to do that, then I think just giving the variable as a value would work:

```r
standardise_country_name <- function(thingy){
  countrycode::countryname(thingy,
                           destination = "country.name.en",
                           nomatch = NA,
                           warn = TRUE)
}
standardise_country_name(data$var)
```

**Comment by chitrams** [comment]
Thanks Nick, this was helpful :)

Closing as this now works.
