### ISSUE TITLE
Use `renv`

### ISSUE THREAD

**Issue by chitrams** [chitrams/conmat-testing#32]
Add `renv` to current pipeline, refer to targets [guide](https://books.ropensci.org/targets/packages.html#package-management-with-renv)

**Comment by njtierney** [comment]
Do we need to add instructions on how to use renv with this, or will it just work?

**Comment by chitrams** [comment]
It simply worked for me. But, I'm going to ask Saras if she can reproduce it as part of our Code Review this week 😃

**Comment by chitrams** [comment]
Updated the readme as well to add instructions on how to use renv with it.
