### ISSUE TITLE
Update README for better readability

### ISSUE THREAD

**Issue by chitrams** [chitrams/conmat-testing#36]
Refer to [Microsoft style guide](https://learn.microsoft.com/en-us/style-guide/procedures-instructions/writing-step-by-step-instructions) for writing step by step instructions

**Comment by njtierney** [comment]
The [README guide in R packages](https://r-pkgs.org/other-markdown.html#sec-readme) is also quite nice

**Comment by chitrams** [comment]
> The [README guide in R packages](https://r-pkgs.org/other-markdown.html#sec-readme) is also quite nice

Ooh thank you, I haven't seen this!
